services:
  frontend_test:
    profiles: ["test"]
    build:
      context: ./frontend
      target: test
    depends_on:
      backend: { condition: service_healthy }
    env_file: [ ./.env.dev ]
    environment:
      NEXT_PUBLIC_PARAM_SYNC_DEBUG: "1"
    command: ["npm","run","test:fast"]
