version: "3.9"

services:
  postgres:
    env_file:
      - .env.dev

  keycloak:
    env_file:
      - .env.dev

  backend:
    env_file:
      - backend/.env
      - .env.dev
    environment:
      REDIS_URL: "redis://redis:6379/0"
      RAG_BM25_ENABLED: "0"
      RAG_BM25_INDEX: "sealai:bm25"

  frontend:
    # absichtlich kein env_file, damit .env.dev NICHT greift
    environment: {}

  nginx:
    env_file:
      - .env.dev
