services:
  backend:
    image: ${BACKEND_IMAGE}
    pull_policy: always
    env_file:
      - ./.env.prod
    environment:
      RAG_UPLOAD_DIR: "/app/data/uploads"
    volumes:
      - backend-data:/app/data
  frontend:
    profiles: ["frontend-container"]
    image: ${FRONTEND_IMAGE}
    pull_policy: always
  keycloak:
    image: ${KEYCLOAK_IMAGE}
    pull_policy: always
    env_file: [ ./.env.prod ]
volumes:
  backend-data:
