services:
  keycloak:
    # DEV: publish
    ports: ["8080:8080"]

  backend:
    # DEV: publish
    ports: ["8000:8000"]

  frontend:
    # DEV: publish
    ports: ["3000:3000"]

  qdrant:
    # DEV: publish (nur wenn du wirklich von außen testen willst)
    ports: ["6333:6333", "6334:6334"]

  frontend_test:
    profiles: ["test"]
    build:
      context: ./frontend
      target: test
    depends_on:
      backend: { condition: service_healthy }
    env_file: [ ./.env.dev ]
    environment:
      NEXT_PUBLIC_PARAM_SYNC_DEBUG: "1"
    command: ["npm","run","test:fast"]
