export interface SealParameters {
  medium?: string;
  pressure_bar?: number | string;
  pressure?: number | string;
  temperature_C?: number | string;
  temperature_max?: number | string;
  temperature_min?: number | string;
  shaft_diameter?: number | string;
  housing_diameter?: number | string;
  speed_rpm?: number | string;
  d_shaft_nominal?: number | string;
  shaft_tolerance?: number | string;
  shaft_hardness?: string;
  shaft_material?: string;
  shaft_Ra?: number | string;
  shaft_Rz?: number | string;
  shaft_lead?: string;
  shaft_runout?: number | string;
  shaft_chamfer?: string;
  d_bore_nominal?: number | string;
  housing_tolerance?: number | string;
  housing_surface_roughness?: string;
  housing_material?: string;
  housing_axial_space?: number | string;
  medium_type?: string;
  medium_viscosity?: string;
  medium_additives?: string;
  medium_solid_content?: string;
  medium_food_grade?: string;
  medium_elastomer_notes?: string;
  n_min?: number | string;
  n_max?: number | string;
  v_max?: number | string;
  p_min?: number | string;
  p_max?: number | string;
  T_medium_min?: number | string;
  T_medium_max?: number | string;
  T_ambient_min?: number | string;
  T_ambient_max?: number | string;
  misalignment?: string;
  vibration_level?: string;
  contamination_level?: string;
  IP_requirement?: string;
  water_exposure?: string;
  chemicals_outside?: string;
  target_lifetime?: string;
  max_leakage?: string;
  max_friction_torque?: string;
  safety_factors?: string;
  install_method?: string;
  access_level?: string;
  expected_service_interval?: string;
  seal_type?: string;
  lip_config?: string;
  elastomer_material?: string;
  spring_material?: string;
  outer_case_type?: string;
  dust_lip?: string;
  helix_direction?: string;
  standard_reference?: string;

  // New fields from refactored form
  nominal_diameter?: number | string;
  tolerance?: number | string;
  hardness?: string;
  surface?: string;
  roughness_ra?: number | string;
  lead?: string;
  lead_pitch?: string;
  runout?: number | string;
  eccentricity?: string;
  
  bore_diameter?: number | string;
  housing_surface?: string;
  axial_plate_axial?: number | string;

  pressure_min?: number | string;
  pressure_max?: number | string;
  temp_min?: number | string;
  temp_max?: number | string;
  speed_linear?: number | string;
  dynamic_runout?: number | string;
  mounting_offset?: number | string;

  contamination?: string;
  lifespan?: string;
  application_type?: string;
  food_grade?: string;
}
