from __future__ import annotations

import base64
import datetime as dt
import hashlib
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

import pytest


REPO = Path(__file__).resolve().parents[2]
MODULE_PATH = REPO / "ops" / "supply_chain_gate.py"
LOCK_HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    ops/update-python-locks.sh\n"
)


def _module():
    spec = importlib.util.spec_from_file_location("supply_chain_gate", MODULE_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


GATE = _module()


def _write_json(path: Path, value: object) -> Path:
    path.write_text(json.dumps(value), encoding="utf-8")
    return path


def _utc(value: dt.datetime) -> str:
    return value.astimezone(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _exception(*, version: str = "0.139.0") -> dict[str, object]:
    approved = dt.datetime.now(dt.timezone.utc) - dt.timedelta(hours=1)
    item = {
        "exception_id": "SCX-2026-999",
        "control": "python-vulnerability",
        "scope": "backend-v2-runtime",
        "advisory_id": "PYSEC-FIXTURE",
        "package": "fastapi",
        "installed_version": version,
        "approved_by": "github:security-owner",
        "reason": "Temporary exact fixture approval while the tracked fix lands.",
        "approved_at": _utc(approved),
        "expires_at": _utc(approved + dt.timedelta(days=7)),
        "tracking_url": "https://github.com/jungt72/sealAI/issues/9999",
    }
    return _bind_receipt(item)


def _bind_receipt(item: dict) -> dict:
    item.pop("approval_receipt", None)
    item["approval_receipt"] = {
        "schema_version": 1,
        "status": "BLOCKED_EXTERNAL",
        "exception_sha256": GATE.canonical_exception_sha256(item),
        "principal": item["approved_by"],
        "review_commit_sha": "a" * 40,
        "review_url": item["tracking_url"],
    }
    return item


def _exception_registry(exceptions: list[dict]) -> dict:
    return {
        "schema_version": 2,
        "approval_verification": "BLOCKED_EXTERNAL",
        "exceptions": exceptions,
    }


def _pip_report() -> dict:
    locked = GATE._locked_requirements(REPO / "backend" / "requirements-v2.lock")
    return {
        "dependencies": [
            {
                "name": name,
                "version": version,
                "vulns": [{"id": "PYSEC-FIXTURE"}] if name == "fastapi" else [],
            }
            for name, version in locked.items()
        ]
    }


def test_repository_policy_and_all_lock_inventories_verify():
    GATE.verify_repository()


def test_required_check_receipt_is_canonical_and_explicitly_blocked_external(
    tmp_path: Path,
):
    GATE.verify_external_governance(REPO)
    github = tmp_path / ".github"
    github.mkdir()
    receipt = json.loads(GATE.REQUIRED_CHECKS_PATH.read_text(encoding="utf-8"))
    receipt["enforcement_receipt"]["status"] = "verified"
    _write_json(github / "required-security-checks.json", receipt)
    (github / "CODEOWNERS").write_text(
        (REPO / ".github" / "CODEOWNERS").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    with pytest.raises(GATE.SupplyChainError, match="BLOCKED_EXTERNAL"):
        GATE.verify_external_governance(tmp_path)


def test_python_audit_collects_the_exact_lock_without_pip_resolution():
    workflow = (REPO / ".github" / "workflows" / "dependency-audit.yml").read_text(
        encoding="utf-8"
    )
    assert "--no-deps" in workflow
    assert "--disable-pip" in workflow
    assert "--strict" in workflow


def test_workflow_gate_rejects_moving_actions_and_unhashed_installs(tmp_path: Path):
    workflows = tmp_path / ".github" / "workflows"
    workflows.mkdir(parents=True)
    workflow = workflows / "fixture.yml"
    workflow.write_text(
        """name: fixture
on: [push]
permissions:
  contents: read
jobs:
  fixture:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
""",
        encoding="utf-8",
    )
    with pytest.raises(GATE.SupplyChainError, match="commit-pinned"):
        GATE.verify_ci_workflows(tmp_path)

    workflow.write_text(
        workflow.read_text(encoding="utf-8").replace(
            "actions/checkout@v7", "actions/checkout@" + "a" * 40
        )
        + "      - run: python -m pip install pytest==9.0.3\n",
        encoding="utf-8",
    )
    with pytest.raises(GATE.SupplyChainError, match="unhashed Python install"):
        GATE.verify_ci_workflows(tmp_path)


def test_trivy_license_config_cannot_add_ignored_licenses(tmp_path: Path):
    security = tmp_path / "security"
    security.mkdir()
    (security / "trivy.yaml").write_text(
        "license:\n"
        "  confidenceLevel: 0.9\n"
        "  full: true\n"
        "  ignored: [AGPL-3.0-only]\n",
        encoding="utf-8",
    )
    with pytest.raises(GATE.SupplyChainError, match="license policy config drifted"):
        GATE.verify_trivy_config(tmp_path)


def test_policy_cannot_remove_a_blocking_severity(tmp_path: Path):
    policy = GATE.load_policy()
    policy["audit_policy"]["image_fail_severities"] = []
    path = _write_json(tmp_path / "policy.json", policy)

    with pytest.raises(GATE.SupplyChainError, match="weakened or drifted"):
        GATE.load_policy(path)


def test_python_lock_requires_a_hash_for_every_entry(tmp_path: Path):
    lock = tmp_path / "requirements.lock"
    lock.write_text(
        LOCK_HEADER + "example==1.2.3 \\\n    # deliberately missing hash\n",
        encoding="utf-8",
    )

    with pytest.raises(GATE.SupplyChainError, match="no valid SHA-256 hash"):
        GATE._locked_requirements(lock)


def test_python_lock_rejects_alternate_package_source(tmp_path: Path):
    lock = tmp_path / "requirements.lock"
    lock.write_text(
        LOCK_HEADER
        + "--extra-index-url https://packages.example.invalid/simple\n"
        + "example==1.2.3 \\\n    --hash=sha256:"
        + "a" * 64
        + "\n",
        encoding="utf-8",
    )

    with pytest.raises(GATE.SupplyChainError, match="unapproved Python lock source"):
        GATE._locked_requirements(lock)


def test_exception_is_blocked_without_external_principal_verification(tmp_path: Path):
    policy = GATE.load_policy()
    exception_path = _write_json(
        tmp_path / "exceptions.json",
        _exception_registry([_exception()]),
    )
    report_path = _write_json(
        tmp_path / "pip-audit.json",
        _pip_report(),
    )

    with pytest.raises(GATE.SupplyChainError, match="BLOCKED_EXTERNAL"):
        GATE.evaluate_report(
            "pip-audit",
            report_path,
            scope="backend-v2-runtime",
            policy_path=GATE.POLICY_PATH,
            exceptions_path=exception_path,
        )
    with pytest.raises(GATE.SupplyChainError, match="BLOCKED_EXTERNAL"):
        GATE.load_exceptions(policy, exception_path)


def test_exception_receipt_hash_rejects_subject_tampering(tmp_path: Path):
    exception = _exception(version="0.138.0")
    exception["installed_version"] = "0.139.0"
    exception_path = _write_json(
        tmp_path / "exceptions.json",
        _exception_registry([exception]),
    )
    report_path = _write_json(
        tmp_path / "pip-audit.json",
        _pip_report(),
    )

    with pytest.raises(GATE.SupplyChainError, match="invalid or unbound"):
        GATE.evaluate_report(
            "pip-audit",
            report_path,
            scope="backend-v2-runtime",
            exceptions_path=exception_path,
        )


def test_expired_or_non_person_bound_exception_fails_closed(tmp_path: Path):
    policy = GATE.load_policy()
    now = dt.datetime.now(dt.timezone.utc)
    expired = _exception()
    expired["approved_at"] = _utc(now - dt.timedelta(days=2))
    expired["expires_at"] = _utc(now - dt.timedelta(days=1))
    _bind_receipt(expired)
    path = _write_json(
        tmp_path / "exceptions.json",
        _exception_registry([expired]),
    )
    with pytest.raises(GATE.SupplyChainError, match="expired"):
        GATE.load_exceptions(policy, path, now=now)

    expired["approved_at"] = _utc(now - dt.timedelta(hours=1))
    expired["expires_at"] = _utc(now + dt.timedelta(days=1))
    expired["approved_by"] = "security-team"
    _bind_receipt(expired)
    _write_json(path, _exception_registry([expired]))
    with pytest.raises(GATE.SupplyChainError, match="GitHub principal"):
        GATE.load_exceptions(policy, path, now=now)


@pytest.mark.parametrize(
    ("scanner", "report"),
    [
        ("pip-audit", {}),
        (
            "npm-audit",
            {"auditReportVersion": 2, "error": {"message": "registry failed"}},
        ),
        ("trivy", {"SchemaVersion": 2, "Results": []}),
    ],
)
def test_missing_or_malformed_scanner_output_fails_closed(
    scanner: str, report: dict, tmp_path: Path
):
    path = _write_json(tmp_path / "report.json", report)
    with pytest.raises(GATE.SupplyChainError):
        GATE.evaluate_report(scanner, path, scope="fixture")


def test_trivy_critical_cve_and_critical_license_are_blocking_findings():
    report = {
        "SchemaVersion": 2,
        "ArtifactName": "fixture-image",
        "ArtifactType": "container_image",
        "Results": [
            {
                "Target": "fixture-image",
                "Vulnerabilities": [
                    {
                        "Severity": "CRITICAL",
                        "VulnerabilityID": "CVE-2099-0001",
                        "PkgName": "libfixture",
                        "InstalledVersion": "1.0",
                    }
                ],
                "Licenses": [
                    {
                        "Severity": "CRITICAL",
                        "Name": "AGPL-3.0-only",
                        "PkgName": "fixture-package",
                        "Version": "2.0",
                    }
                ],
            }
        ],
    }
    findings = GATE.findings_from_report(
        "trivy", report, scope="fixture-image", root=REPO, policy=GATE.load_policy()
    )

    assert {finding.control for finding in findings} == {
        "image-vulnerability",
        "license",
    }


def test_npm_emits_only_actual_critical_advisory_not_transitive_echoes():
    package_count = len(
        json.loads((REPO / "package-lock.json").read_text(encoding="utf-8"))["packages"]
    )
    report = {
        "auditReportVersion": 2,
        "metadata": {
            "dependencies": {"total": package_count - 1},
            "vulnerabilities": {
                "info": 0,
                "low": 0,
                "moderate": 0,
                "high": 0,
                "critical": 2,
                "total": 2,
            },
        },
        "vulnerabilities": {
            "dependent-package": {
                "severity": "critical",
                "nodes": [],
                "via": ["form-data"],
            },
            "form-data": {
                "severity": "critical",
                "nodes": [],
                "via": [
                    {
                        "severity": "critical",
                        "url": "https://github.com/advisories/GHSA-critical",
                    },
                    {
                        "severity": "high",
                        "url": "https://github.com/advisories/GHSA-high",
                    },
                ],
            },
        },
    }

    findings = GATE.findings_from_report(
        "npm-audit",
        report,
        scope="repository-tooling",
        root=REPO,
        policy=GATE.load_policy(),
    )

    assert {finding.advisory_id for finding in findings} == {
        "https://github.com/advisories/GHSA-critical",
        "https://github.com/advisories/GHSA-high",
    }
    assert {finding.package for finding in findings} == {"form-data"}


def test_scan_predicate_binds_report_policy_and_exception_hashes(tmp_path: Path):
    report_path = _write_json(
        tmp_path / "trivy.json",
        {
            "SchemaVersion": 2,
            "ArtifactName": "fixture-image",
            "ArtifactType": "container_image",
            "Results": [
                {
                    "Target": "fixture-image",
                    "Vulnerabilities": [],
                    "Licenses": [],
                }
            ],
        },
    )
    output = tmp_path / "predicate.json"

    GATE.create_scan_predicate(
        report_path,
        output,
        scope="backend-v2-image",
        artifact_name="ghcr.io/jungt72/sealai-backend-v2",
        artifact_digest="sha256:" + "a" * 64,
        artifact_type="container_image",
        report_artifact_name="fixture-image",
        source_git_sha="b" * 40,
        tree_hash="c" * 40,
    )
    predicate = json.loads(output.read_text(encoding="utf-8"))

    assert predicate["result"] == "pass"
    assert predicate["artifact"]["digest"] == "sha256:" + "a" * 64
    assert predicate["source"] == {"git_sha": "b" * 40, "tree_hash": "c" * 40}
    assert (
        predicate["report_sha256"]
        == hashlib.sha256(report_path.read_bytes()).hexdigest()
    )
    assert (
        predicate["policy_sha256"]
        == hashlib.sha256(GATE.POLICY_PATH.read_bytes()).hexdigest()
    )
    assert (
        predicate["exceptions_sha256"]
        == hashlib.sha256(GATE.EXCEPTIONS_PATH.read_bytes()).hexdigest()
    )


def test_image_reference_requires_tag_and_sha256_digest():
    assert (
        GATE.main(
            [
                "verify-image-ref",
                "ghcr.io/jungt72/sealai-backend-v2:commit@sha256:" + "a" * 64,
            ]
        )
        == 0
    )
    with pytest.raises(SystemExit) as error:
        GATE.main(
            [
                "verify-image-ref",
                "ghcr.io/jungt72/sealai-backend-v2@sha256:" + "a" * 64,
            ]
        )
    assert error.value.code == 2

    with pytest.raises(SystemExit) as wrong_repository:
        GATE.main(
            [
                "verify-image-ref",
                "ghcr.io/example/sealai-backend-v2:commit@sha256:" + "a" * 64,
            ]
        )
    assert wrong_repository.value.code == 2


def test_pip_audit_rejects_a_valid_but_truncated_transitive_inventory():
    report = _pip_report()
    report["dependencies"].pop()
    with pytest.raises(GATE.SupplyChainError, match="exact transitive lock"):
        GATE.findings_from_report(
            "pip-audit",
            report,
            scope="backend-v2-runtime",
            root=REPO,
            policy=GATE.load_policy(),
        )


def test_node_lock_rejects_missing_registry_integrity(tmp_path: Path):
    manifest = {
        "name": "fixture",
        "version": "1.0.0",
        "dependencies": {"fixture": "1.0.0"},
    }
    lock = {
        "name": "fixture",
        "version": "1.0.0",
        "lockfileVersion": 3,
        "packages": {
            "": manifest,
            "node_modules/fixture": {"version": "1.0.0"},
        },
    }
    _write_json(tmp_path / "package.json", manifest)
    lock_path = _write_json(tmp_path / "package-lock.json", lock)
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(
        ["git", "add", "package.json", "package-lock.json"], cwd=tmp_path, check=True
    )
    policy = {"node_projects": [{"name": "fixture", "path": "."}]}
    with pytest.raises(GATE.SupplyChainError, match="missing Node source"):
        GATE.verify_node_locks(tmp_path, policy)

    lock["packages"]["node_modules/fixture"].update(
        {
            "resolved": "https://registry.npmjs.org/fixture/-/fixture-1.0.0.tgz",
            "integrity": "sha512-" + base64.b64encode(b"x" * 64).decode(),
        }
    )
    _write_json(lock_path, lock)
    GATE.verify_node_locks(tmp_path, policy)


def test_materialized_compose_images_reject_wrong_backend_repository(tmp_path: Path):
    manifests = ("docker-compose.yml", "docker-compose.deploy.yml")
    references = []
    for manifest in manifests:
        references.extend(
            repository + ":fixture@sha256:" + "a" * 64
            for repository in GATE._manifest_literal_repositories(REPO / manifest)
        )
    references.extend(
        repository + ":fixture@sha256:" + "b" * 64
        for repository in (
            "ghcr.io/jungt72/sealai-backend-v2",
            "ghcr.io/jungt72/sealai-frontend",
            "ghcr.io/jungt72/sealai-keycloak",
        )
    )
    images = tmp_path / "images.txt"
    images.write_text("\n".join(references) + "\n", encoding="utf-8")
    GATE.verify_materialized_images(manifests, images)

    backend_ref = next(
        reference
        for reference in references
        if reference.startswith("ghcr.io/jungt72/sealai-backend-v2:")
    )
    images.write_text("\n".join(references + [backend_ref]) + "\n", encoding="utf-8")
    GATE.verify_materialized_images(manifests, images)

    images.write_text(
        images.read_text(encoding="utf-8").replace(
            "ghcr.io/jungt72/sealai-backend-v2", "ghcr.io/example/backend-v2"
        ),
        encoding="utf-8",
    )
    with pytest.raises(GATE.SupplyChainError, match="do not match policy"):
        GATE.verify_materialized_images(manifests, images)
