# Re-export shim — canonical location: app.agent.runtime.reply_builder
# DO NOT add logic here. This file exists only for import compatibility.
from app.agent.runtime.reply_builder import (  # noqa: F401
    AMBIGUOUS_CANDIDATE_REPLY,
    DEMO_DATA_QUARANTINE_REPLY,
    ESCALATION_NEEDED_REPLY,
    EVIDENCE_MISSING_REPLY,
    MANUFACTURER_VALIDATION_REPLY,
    NEUTRAL_SCOPE_REPLY,
    NO_CANDIDATES_REPLY,
    NO_VIABLE_CANDIDATES_REPLY,
    PRECHECK_ONLY_REPLY,
    REVIEW_PENDING_REPLY,
    SAFEGUARDED_WITHHELD_REPLY,
    _STRUCTURED_API_EXPOSURE_KEYS,
    _artifact_is_aligned,
    _assert_structured_api_exposure_contract,
    _build_candidate_projection,
    _build_recommendation_artifact,
    _build_recommendation_rationale_summary,
    _can_surface_governed_rationale_reply,
    _find_candidate,
    _minimal_structured_snapshot_contract,
    _minimal_structured_snapshot_from_case_state,
    _normalize_structured_api_exposure_value,
    _resolve_runtime_dispatch_source,
    build_final_reply,
    build_structured_api_exposure,
)
