#!/usr/bin/env bash
#
# Cleanup helper generated by audit Step 4.
# Default mode is dry-run; pass --no-dry-run to actually move files into .trash/<timestamp>/.

set -euo pipefail

DRY_RUN=1
TRASH_ROOT=".trash"
TIMESTAMP="$(date +"%Y%m%dT%H%M%S")"

usage() {
  cat <<'EOF'
Usage: scripts/cleanup.sh [--no-dry-run]

By default this script prints the actions it *would* take.
With --no-dry-run it moves files/directories into .trash/<timestamp>/...

Only run with --no-dry-run after reviewing CLEANUP_REPORT.md and confirming the plan.
EOF
}

if [[ "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if [[ "${1:-}" == "--no-dry-run" ]]; then
  DRY_RUN=0
  shift
fi

if [[ $# -gt 0 ]]; then
  echo "Unexpected argument(s): $*" >&2
  usage
  exit 1
fi

declare -a TARGETS=(
  "backend/agents/material_agent/main.py|Legacy FastAPI micro-app superseded; unused per vulture/deptry"
  "backend/agents/normen_agent/main.py|Legacy FastAPI micro-app superseded; unused per vulture/deptry"
  "backend/app/api/routes/chat.py|Deprecated SSE fallback; LangGraph path replaces it"
  "backend/app/__pycache__|Bytecode artefact"
  "backend/app/langgraph/__pycache__|Bytecode artefact"
  "backend/.pytest_cache|Test artefact"
  "frontend/.next|Next.js build artefact"
  ".pytest_cache|Test artefact"
  ".env.bak.1754931261|Redundant env backup (duplicate hash)"
  ".env.bak.1754931391|Redundant env backup (duplicate hash)"
  ".env.bak.1754931465|Redundant env backup (duplicate hash)"
  "frontend/src/components/Fog.tsx|Unused export (knip/ts-prune)"
  "frontend/src/components/HeroBackground.tsx|Unused export (knip/ts-prune)"
  "frontend/src/components/organisms/Header.tsx|Unused export (knip/ts-prune)"
  "frontend/src/components/organisms/Sidebar.tsx|Unused export (knip/ts-prune)"
  "frontend/src/components/ui/card.tsx|Unused duplicate component (knip/ts-prune)"
  "frontend/src/app/dashboard/Dashboard.tsx|Legacy dashboard wrapper (ts-prune)"
  "frontend/src/app/dashboard/ChatScreen.tsx|Legacy dashboard screen (ts-prune)"
  "frontend/src/app/dashboard/components/Sidebar/Sidebar.tsx|Legacy wrapper (ts-prune)"
  "frontend/src/app/dashboard/components/Sidebar/SidebarRight.tsx|Unused panel (ts-prune)"
  "frontend/src/lib/logout.ts|Unused exports (knip/ts-prune)"
  "frontend/src/lib/useAccessToken.ts|Unused helper (knip/ts-prune)"
)

trash_path() {
  local target="$1"
  printf "%s/%s/%s\n" "$TRASH_ROOT" "$TIMESTAMP" "$target"
}

move_to_trash() {
  local src="$1"
  local dst="$2"

  if [[ ! -e "$src" ]]; then
    echo "skip: $src (does not exist)"
    return
  fi

  if (( DRY_RUN )); then
    echo "dry-run: would move '$src' -> '$dst'"
    return
  fi

  mkdir -p "$(dirname "$dst")"
  mv "$src" "$dst"
  echo "moved: $src -> $dst"
}

echo "Cleanup targets: ${#TARGETS[@]}"
echo "Dry-run mode: $DRY_RUN (1 means enabled)"

for entry in "${TARGETS[@]}"; do
  IFS='|' read -r path reason <<<"$entry"
  echo "----------------------------------------"
  echo "target : $path"
  echo "reason : $reason"
  move_to_trash "$path" "$(trash_path "$path")"
done

echo "----------------------------------------"
echo "Done."
if (( DRY_RUN )); then
  echo "No files were moved. Re-run with --no-dry-run after confirmation."
fi
