# Re-export shim — canonical location: app.agent.state.case_state
# DO NOT add logic here. This file exists only for import compatibility.
from app.agent.state.case_state import (  # noqa: F401
    # Constants
    PROJECTION_VERSION,
    CASE_STATE_BUILDER_VERSION,
    DETERMINISTIC_SERVICE_VERSION,
    DETERMINISTIC_DATA_VERSION,
    QUALIFIED_ACTION_AUDIT_EVENT,
    QUALIFIED_ACTION_DOWNLOAD_RFQ,
    QUALIFIED_ACTION_STATUS_NONE,
    QUALIFIED_ACTION_STATUS_BLOCKED,
    QUALIFIED_ACTION_STATUS_EXECUTED,
    # Type aliases
    QualifiedActionId,
    QualifiedActionLifecycleStatus,
    QualifiedActionAuditEventType,
    # TypedDicts
    VersionProvenance,
    VisibleNarrativeItem,
    VisibleCaseNarrative,
    BoundaryContract,
    CaseMeta,
    CaseState,
    # Public functions
    build_default_candidate_clusters,
    build_default_result_contract,
    build_default_sealing_requirement_spec,
    normalize_qualified_action_id,
    build_dispatch_intent,
    build_case_state,
    sync_case_state_to_state,
    ensure_case_state,
    sync_material_cycle_control,
    get_material_input_snapshot_and_fingerprint,
    get_material_provider_snapshot_and_fingerprint,
    resolve_next_step_contract,
    build_conversation_guidance_contract,
    build_visible_case_narrative,
    # Private helpers (used by consumers)
    _build_recommendation_identity,
    _build_requirement_class_hint,
    _derive_requirement_class_basis,
    _requirement_class_source,
    _build_requirement_class,
    _build_conflict_summary,
    _build_match_candidates,
    _build_matching_blocking_reasons,
    _derive_matchability_status,
    _build_rfq_blocking_reasons,
    _build_rfq_open_points,
    _build_manufacturer_refs,
    _build_manufacturer_capabilities,
    _build_recipient_selection,
    _infer_unit,
    _normalize_snapshot_value,
    _resolve_selected_partner_id,
    _current_medium_label,
    _resolve_medium_context,
    _coverage_prefix,
    _build_visible_coverage_scope,
)
