name: deploy
on:
  workflow_run:
    workflows: [ build-and-push ]
    types: [ completed ]
    branches: [ main, refactor/intake-triage-unify ]
permissions:
  contents: read
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -euxo pipefail
            cd /root/sealai
            docker compose pull backend frontend keycloak || true
            docker compose up -d backend frontend keycloak
            docker system prune -f
            curl -fsS http://localhost:8000/api/v1/ping || curl -fsS http://localhost:8000/health || true
