name: manual-deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Git branch to deploy"
        required: true
        default: "refactor/intake-triage-unify"
      force_clean:
        description: "Force clean working tree before deploy"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -euxo pipefail
            BRANCH="${{ github.event.inputs.branch }}"
            FORCE="0"
            if [[ "${{ github.event.inputs.force_clean }}" == "true" ]]; then
              FORCE="1"
            fi
            cd /root/sealai
            if [[ ! -x scripts/deploy_sync.sh ]]; then
              git fetch origin
              git checkout "${BRANCH}"
              git pull --ff-only origin "${BRANCH}"
              chmod +x scripts/deploy_sync.sh || true
            fi
            FORCE_DEPLOY="${FORCE}" ./scripts/deploy_sync.sh "${BRANCH}"
